Implement homework-2
Kkkkkk58/TinkoffFintechJava pull request #2
Opened 2023-09-21 21:00 UTC by Kkkkkk58

2023-09-24 15:51 UTC, madoed requested changes

2023-09-24 15:51 UTC, madoed commented on fintech/src/main/java/ru/kslacker/fintech/models/Weather.java
> +    private int temperatureValue;
Думаю стоит поменять на другой тип данных, т.к. обычно для хранения значения температуры используют не целое значение.

2023-09-24 15:51 UTC, madoed commented on fintech/src/main/java/ru/kslacker/fintech/service/WeatherServiceImpl.java
> +public class WeatherServiceImpl implements WeatherService {
Если реализация одна у интерфейса, то можно не использовать интерфейс

2023-09-24 15:51 UTC, madoed commented on fintech/src/test/java/ru/kslacker/fintech/service/WeatherServiceImplTest.java
> +        assertEquals(-3, result.get(region2));
Можно объединить в assertAll если проверок несколько

2023-09-24 16:03 UTC, Kkkkkk58 commented on fintech/src/main/java/ru/kslacker/fintech/models/Weather.java
> +    private int temperatureValue;
В чатике вроде ответили, что можно использовать целочисленные значения

2023-09-24 16:11 UTC, Kkkkkk58 commented on fintech/src/main/java/ru/kslacker/fintech/service/WeatherServiceImpl.java
> +public class WeatherServiceImpl implements WeatherService {
Хочется не завязываться на детали реализации и соблюдать принцип DI, закладывать точки расширения с самого начала намного удобнее

2023-09-25 06:59 UTC, madoed commented on fintech/src/main/java/ru/kslacker/fintech/models/Weather.java
> +    private int temperatureValue;
Ну логичнее всего использовать double, как ты сейчас и сделал. За чатиком не слежу

2023-09-25 07:00 UTC, madoed approved these changes
Всё отлично

2023-09-25 07:05 UTC, madoed commented on fintech/src/main/java/ru/kslacker/fintech/service/WeatherServiceImpl.java
> +public class WeatherServiceImpl implements WeatherService {
Ну тут я больше опираюсь на принцип KISS

Нет смысла усложнять программу, без надобности. Плюс, в будущем, если появится необходимость добавления второй реализации, то стоимость доработки - добавления новой реализации + выделения интерфейса будет стоить дешево.

Так же, когда интерфейс + 1 реализация будет оправдана с самого начала - это случай, когда проектируем библиотеку в которой закладываем возможность реализации пользователем этого интерфейса

2023-10-01 09:12 UTC, merged